### PR TITLE
Fixed casting bug when creating a spinner progress dialog.

### PR DESCRIPTION
**Pull request by waninkoko**

### CODE REVIEW

**Comment by Prototik** [comment]
Cast bug? You sure? Where? LayoutInflater always inflate <LinearLayout> tag as com.WazaBe.HoloEverywhere.widget.LinearLayout.

**Comment by indieboyalex** [comment]
I am also getting:

E/AndroidRuntime(32760): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pocketwriters/com.pocketwriters.ReaderActivity}: java.lang.ClassCastException: android.widget.LinearLayout

[.....]

E/AndroidRuntime(32760): Caused by: java.lang.ClassCastException: android.widget.LinearLayout
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.internal.AlertController.setupView(AlertController.java:720)
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.internal.AlertController.installContent(AlertController.java:449)
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.app.AlertDialog.onCreate(AlertDialog.java:352)
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.app.ProgressDialog.onCreate(ProgressDialog.java:215)
E/AndroidRuntime(32760):    at android.app.Dialog.dispatchOnCreate(Dialog.java:319)
E/AndroidRuntime(32760):    at android.app.Dialog.show(Dialog.java:237)
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.app.ProgressDialog.show(ProgressDialog.java:49)
E/AndroidRuntime(32760):    at com.WazaBe.HoloEverywhere.app.ProgressDialog.show(ProgressDialog.java:37)
E/AndroidRuntime(32760):    at com.pocketwriters.tasks.ChapterLoaderTask.onPreExecute(ChapterLoaderTask.java:110)
E/AndroidRuntime(32760):    at android.os.AsyncTask.execute(AsyncTask.java:391)
E/AndroidRuntime(32760):    at com.pocketwriters.ReaderActivity.onCreate(ReaderActivity.java:68)
E/AndroidRuntime(32760):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime(32760):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)

**Comment by indieboyalex** [comment]
Just noticed (I'm using the dev branch BTW), that this is effecting the Preference activity dialogs I'm creating, so this is obviously related to a fairly recent change in the code as we got these working perfectly a couple of weeks ago.

**Comment by stleusc** [comment]
Maybe similar issue:

10-12 00:35:10.596: E/AndroidRuntime(8276): Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.WazaBe.HoloEverywhere.widget.LinearLayout
10-12 00:35:10.596: E/AndroidRuntime(8276):     at com.WazaBe.HoloEverywhere.internal.AlertController.setupView(AlertController.java:720)

the used xml uses android LinearLayout but code uses HoloEverywhere Linearlayout!

**Pull request closed without merging**
