### PR TITLE
VerifyError fixed on Android 1.6

### PR DESCRIPTION
**Pull request by ripdajacker**
Wasn't able to run the dialog using 

AlertDialog.Builder builder = //
builder.create(); <--- Failed

One of the constructors failed in the stock 1.6. 

I removed the annotations, but not sure if they broke anything.

### CODE REVIEW

**Comment by Prototik** [comment]
Why did you remove the constructor DialogButtonBar(Context context, AttributeSet attrs, int defStyle)?

**Comment by ripdajacker** [comment]
Yeah, it wouldn't compile on 1.6

**Comment by Prototik** [comment]
Yes, the constructor View(Context, AttributeSet, int) appeared only in 2.2 (or 2.1, can not remember).
But that is no reason to remove it from the library.
Code will be compiled under the target sdk > 11 and run on a 1.6 normally.

**Comment by ripdajacker** [comment]
You are probably right, it was a very quick fix.

The issue remains elsewhere then. It did compile, but when the other
constructor was called, it died with a verify error.
This only happened on 1.6, my 2.1 emulator ran it fine.

On Sat, Sep 1, 2012 at 11:26 AM, Sergey notifications@github.com wrote:

> Yes, the constructor View(Context, AttributeSet, int) appeared only in 2.2
> (or 2.1, can not remember).
> But that is no reason to remove it from the library.
> Code will be compiled under the target sdk > 11 and run on a 1.6 normally.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ChristopheVersieux/HoloEverywhere/pull/56#issuecomment-8211420.

## 

Jesenko Mehmedbašić
M: +45 30 243 678
jesenko@mehmedbasic.dk

**Comment by Prototik** [comment]
dbca48a6ac92ba049881f7260529ebd5b609bf6f

**Pull request closed without merging**
