### PR TITLE
fix listview selector

### PR DESCRIPTION
**Pull request by saik0**
- changes listview selector to holo style
- import some resource depends

Note: default text appearance makes selected list row text color inverted

### CODE REVIEW

**Comment by ChristopheVersieux** [comment]
"This pull request cannot be automatically merged."
I will try to find what's wrong saturday or sunday and merge your changes, thank a lot for your help!

**Comment by saik0** [comment]
Strange. Added another commit to fix the textColors to match Holo too.

**Comment by Prototik** [comment]
https://github.com/ChristopheVersieux/HoloEverywhere/pull/54

**Comment by saik0** [comment]
also fixed scrollbar style. Thats it for me for tonight!

**Pull request merged**
