### PR TITLE
Fix backwards AlertDialog button behavior

### PR DESCRIPTION
**Pull request by croemmich**

### CODE REVIEW

**Comment by Prototik** [comment]
Hmm. No, I'm not planning to. Method `addButtonBehavior` adds flag which dismiss dialog after pressing the button. A `removeButtonBehavior` removes this behavior. Isn't it?

**Comment by croemmich** [comment]
If your goal is to dismiss the dialog if the flag is set, then your default button behavior should be 14 (1110) to maintain backwards compatibility. In addition, setBlockDismiss will work backwards.

**Comment by Prototik** [comment]
But default button behavior [exaclty](https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/internal/AlertController.java#L102) 1110, isn't it?

**Comment by croemmich** [comment]
Yes, my mistake, I was looking here: https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/library/src/org/holoeverywhere/app/AlertDialog.java#L98

setBlockDismiss should just setButtonBehavior(0) then, not?

**Pull request closed without merging**
