### PR TITLE
Delete/Ignore bin and gen folders

### PR DESCRIPTION
**Pull request by navarr**
These folders are generated by Java on build and are not necessary for version control.  They can safely be removed and ignored from the control system and consistently built client-side.

### CODE REVIEW

**Comment by ChristopheVersieux** [comment]
Thank a  lot!

**Comment by navarr** [comment]
I've added this to v1.2 of my app: https://play.google.com/store/apps/details?id=me.navarr.japanumber

**Comment by ChristopheVersieux** [comment]
As this is the first time I create a public project, are you satisfied with
it and the way I shared it?

Was it difficult for you to use it?

I am so glad that my project helped someone and will keep you updated with
the improvement.

Thank a lot.

Christophe
On Mar 11, 2012 10:24 AM, "Navarr Barnier" <
reply@reply.github.com>
wrote:

**Comment by navarr** [comment]
It was really easy to install and use.  The only issue I had was with ActionBarSherlock and that's only because I didn't read the instructions fully.

It's great that its here, if other people find and like it they're sure to contribute to it - if there isn't already a more popular project that does the same.

**Comment by ChristopheVersieux** [comment]
Thank a lot for your precious help!

**Pull request merged**
