### PR TITLE
Fixed GridView inflation error on devices running Android with API 10 or below

### PR DESCRIPTION
**Pull request by kofi-de-com**
setChoiceMode() is only present in AbsListView since API 11

### CODE REVIEW

**Comment by Prototik** [comment]
Hm... Added in API 1
S
[Docs](http://developer.android.com/reference/android/widget/AbsListView.html#setChoiceMode%28int%29)

**Comment by kofi-de-com** [comment]
I know, the docs are wrong see https://code.google.com/p/android/issues/detail?id=53688&q=setchoicemode&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

**Comment by kofi-de-com** [comment]
or try to find the function here https://github.com/android/platform_frameworks_base/blob/android-2.2_r1.1/core/java/android/widget/AbsListView.java

**Comment by Prototik** [comment]
Well...

**Pull request merged**
