### PR TITLE
Issue#549

### PR DESCRIPTION
**Pull request by william-ferguson-au**
This will stop the crashes due to use of the unavailable Drawable#getCallback method.
But I'm not sure it the RotateDrawable component will work as intended without being able to invoke the Callback.

### CODE REVIEW

**Comment by Prototik** [comment]
Squash your commits first.

**Comment by william-ferguson-au** [comment]
What do you want me to squash? When I try to rebase I only have 107bcfc and 5b0df85 and about hundred commits that have been merged from upstream.

**Comment by BraisGabin** [comment]
Something like:

``` git
git reset HEAD^1 --soft
git stash
git reset HEAD^1 --hard
# rebase
git stash pop
git commit -a -m "Stops RotateDrawable from calling API that doesn't exist on Android 2.3 or below."
# squash
```

I'm pretty sure that there is a better way but...

**Comment by william-ferguson-au** [comment]
Thanks guys. Think I have it correct now. New pull request submitted.

**Pull request closed without merging**
